<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Safe.WinForms.Native.PInvoke.UXTHEME</Title>
    <Authors>Spearton-CS</Authors>
    <Product>WinForms.Native.Safe</Product>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\PInvoke\WinForms.Native.PInvoke.UXTHEME\WinForms.Native.PInvoke.UXTHEME.csproj" />
    <ProjectReference Include="..\WinForms.Native.PInvoke.Safe\WinForms.Native.PInvoke.Safe.csproj" />
  </ItemGroup>

</Project>
