<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>WinForms.Native</Title>
    <Authors>Spearton-CS</Authors>
    <Product>WinForms.Native</Product>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <IsTrimmable>True</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <IsTrimmable>True</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RequiredModules\PInvoke\WinForms.Native.PInvoke.KERNEL32\WinForms.Native.PInvoke.KERNEL32.csproj" />
    <ProjectReference Include="..\RequiredModules\PInvoke\WinForms.Native.PInvoke.USER32\WinForms.Native.PInvoke.USER32.csproj" />
    <ProjectReference Include="..\RequiredModules\PInvoke\WinForms.Native.PInvoke\WinForms.Native.PInvoke.csproj" />
    <ProjectReference Include="..\RequiredModules\WinForms.Native.Extensions\WinForms.Native.Extensions.csproj" />
  </ItemGroup>

</Project>
